language: python
python:
  - 2.7
  - 3.6

addons:
  apt:
    packages:
    - python-dev
    - python3-dev

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  # Clone public samples
  - git clone https://github.com/theopolis/uefi-firmware-samples samples

script:
  # Run the unittests
  - python -bb ./tests/test_compression.py

  # Run a test script against all samples
  - (cd samples && python -bb ./test_samples.py)
